[package]
name = "day-19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"
lib = { path = "../lib/" }
nohash-hasher = "0.2.0"
rustc-hash = "1.1.0"
thiserror = { workspace = true }
